export const type = {
    GET_CLIENTES: "GET_CLIENTES",
    GET_CLIENTE: "GET_CLIENTE",
    POST_CLIENTES: "POST_CLIENTES",
    GET_SOLICITUDES: "GET_SOLICITUDES",
    GET_SOLICITUD: "GET_SOLICITUD",
    POST_SOLICITUD: "POST_SOLICITUD",
    GET_ACTIVIDAD: "GET_ACTIVIDAD",
    GET_ACTIVIDADES: "GET_ACTIVIDADES",
    POST_ACTIVIDADES: "POST_ACTIVIDADES",
    GET_REVIEW: "GET_REVIEW",
    GET_REVIEWS: "GET_REVIEWS",
    POST_REVIEWS: "POST_REVIEWS",
    GET_SERVICIO: "GET_SERVICIO",
    GET_SERVICIOS: "GET_SERVICIOS",
    POST_SERVICIO: "POST_SERVICIO",
    CREATE_SERVICIO: "CREATE_SERVICIO",
    STAT_CHANGE: "STAT_CHANGE",
    ERROR: "ERROR",
    ORDER_N: "ORDER_N",
    ORDER_A: "ORDER_A"
  };
  